import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <header className="bg-gray-600 text-white p-4 shadow-md">
            <div className="max-w-6xl mx-auto">
                <Link href="/"
                      className="text-xl font-semibold hover:no-underline hover:text-gray-300 transition-colors">
                    ← Back to Home
                </Link>
            </div>
        </header>
        {children}
        </body>
        </html>
    );
}
